### PR TITLE
Pre-signed URL was available to everyone (for 4.1-stable)

### PR DESCRIPTION
**Pull request by yui-har**
When the proxy option is disabled, the pre-signed URL will be known to Redmine users. It is very dangerous.
The following changes have been made:
* Delete proxy option
* Return actual data without using pre-signed URL

Please after merging, change the branch name from "4.1-trunk" to "4.1-stable".

### CODE REVIEW

**Comment by yoshiokaCB** [comment]
RedmineS3::Connection#object_url は利用されないと思うので削除を検討してみてはいかがでしょうか？
https://github.com/farend/redmine_s3/pull/3/files#diff-b45ec54717b0ea241467b5bab47f6d18R72

また、削除する場合、下記の設定も不要になるかと思います。
https://github.com/farend/redmine_s3/pull/3/files#diff-7383a5c515d362f307c4dc79d7ea67fbR8
https://github.com/farend/redmine_s3/pull/3/files#diff-b45ec54717b0ea241467b5bab47f6d18L17

**Comment by yui-har** [comment]
> RedmineS3::Connection#object_url は利用されないと思うので削除を検討してみてはいかがでしょうか？
> https://github.com/farend/redmine_s3/pull/3/files#diff-b45ec54717b0ea241467b5bab47f6d18R72

RedmineS3::Connection#object_url を含め未使用メソッド・オプション等を削除します。

**Comment by yui-har** [comment]
The changes are as follows:
* Delete `Redmine::Connection.get` .
* Delete `Redmine::Connection.object_url` .
* Delete `expires` option.

**Comment by yui-har** [comment]
Removed the `private` option.

**Comment by yoshiokaCB** [comment]
Thanks for the PR.

**Comment by yui-har** [comment]
> Please after merging, change the branch name from "4.1-trunk" to "4.1-stable".

@yoshiokaCB Could you change the branch name?

**Comment by yoshiokaCB** [comment]
Would I rename to 4.1-stable?
( 4.1-trunk to 4.1-stable )

**Comment by yui-har** [comment]
> Would I rename to 4.1-stable?
> ( 4.1-trunk to 4.1-stable )

Yes, that's right. 
After renaming, please merge 4.1-stable into master. The master will be up to date.

**Pull request merged**
